# Generated by Django 5.1.3 on 2024-11-14 02:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_type_infer_api', '0002_remove_datafile_update_date_datafile_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='columndatatype',
            name='column_id',
        ),
        migrations.AddField(
            model_name='columndatatype',
            name='column_name',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
